### ISSUE TITLE
outpost deployment via docker prodouces invalid traefik label

### ISSUE THREAD

**Issue by dalamudx** [goauthentik/authentik#11352]
**Describe the bug**
outpost deployment via docker prodouces invalid traefik label with double "`"

**To Reproduce**

1. Go to 'outpost' and create outpost
   my config
```
log_level: info
docker_labels: null
authentik_host: https://auth.xxxxxx.com/
docker_network: traefik
container_image: reg.xxxxxx.com/goauthentik/proxy:2024.8.1
docker_map_ports: true
kubernetes_replicas: 1
kubernetes_namespace: default
authentik_host_browser: ""
object_naming_template: ak-outpost-%(name)s
authentik_host_insecure: true
kubernetes_json_patches: null
kubernetes_service_type: ClusterIP
kubernetes_image_pull_secrets: []
kubernetes_ingress_class_name: null
kubernetes_disabled_components: []
kubernetes_ingress_annotations: {}
kubernetes_ingress_secret_name: authentik-outpost-tls
```
2. Check the outpost docker label
![image](https://github.com/user-attachments/assets/60c74572-b886-48f3-a1e6-24f9e59fe090)
3. Traefik side
![image](https://github.com/user-attachments/assets/74974587-a8d9-41a0-ad87-d9cde14a9d99)
4. Invalid traefik label
```
(Host(``traefik.xxxxxx.com``)) && PathPrefix(`/outpost.goauthentik.io`)
```
**Expected behavior**
so the label should be
```Host(`traefik.xxxxxx.com`) && PathPrefix(`/outpost.goauthentik.io`)```
or
```(Host(`traefik.xxxxxx.com`)) && PathPrefix(`/outpost.goauthentik.io`)```
**Screenshots**

**Logs**
```
2024-09-12T15:44:14+08:00 ERR error="error while parsing rule (Host(``traefik.xxxxxx.com``)) && PathPrefix(`/outpost.goauthentik.io`): 1:9: missing ',' in argument list" entryPointName=https routerName=ak-outpost-core-router@docker
2024-09-12T15:44:14+08:00 ERR error="invalid rule (Host(``traefik.xxxxxx.com``)) && PathPrefix(`/outpost.goauthentik.io`), error: error while parsing rule (Host(``traefik.xxxxxx.com``)) && PathPrefix(`/outpost.goauthentik.io`): 1:9: missing ',' in argument list" entryPointName=https routerName=ak-outpost-core-router@docker
```

**Version and Deployment (please complete the following information):**

-   authentik version: 2024.8.1
-   Deployment: docker-compose

**Additional context**

**Comment by dalamudx** [comment]
fixed https://github.com/goauthentik/authentik/pull/11460
remove current outpost container and update outpost on portal

**Comment by amour86** [comment]
I deleted the container and i've updated the outpost. still the same
