### ISSUE TITLE
Yubikey without pin fails to log in

### ISSUE THREAD

**Issue by tbbkitty** [goauthentik/authentik#11369]
**Describe the bug**
Registering a Yubikey without a pin works fine, however if a user tries to log in with it authentik just reloads the auth request over and over again and the user is stuck in an infinite loop of the browser asking you to touch the key.

This is an issue when I have verified that user authentication is not required. 

**To Reproduce**

1. Use Firefox to register a new Yubikey without a pin
2. Use the same Yubikey to log in.
3. Loop

**Expected behavior**
The user should be able to log in despite of this.

**Screenshots**
N/A

**Logs**
```
{"domain_url": null, "event": "Task started", "level": "info", "logger": "authentik.root.celery", "pid": 901, "schema_name": "public", "task_id": "cd63de0d-0070-462d-9db2-64dd3e892648", "task_name": "event_trigger_handler", "timestamp": "2024-09-13T10:44:46.048490"}
{"domain_url": null, "event": "Task finished", "level": "info", "logger": "authentik.root.celery", "pid": 901, "schema_name": "public", "state": "SUCCESS", "task_id": "cd63de0d0070462d9db264dd3e892648", "task_name": "event_trigger_handler", "timestamp": "2024-09-13T10:44:46.073714"}
{"domain_url": null, "event": "Task finished", "level": "info", "logger": "authentik.root.celery", "pid": 972, "schema_name": "public", "state": "SUCCESS", "task_id": "3a1e9f79fa4d44949380cfd9eba5b0b5", "task_name": "event_trigger_handler", "timestamp": "2024-09-13T10:44:46.084665"}
```
The logs say that the authentication is successful 

**Version and Deployment (please complete the following information):**

-   authentik version: 2024.6.4
-   Deployment: docker-compose

**Additional context**
N/A

**Comment by BeryJu** [comment]
Could you post screenshots of both the configuration of the webauthn authenticator setup stage and the authenticator validation stage? There might be conflicting options which make it not require a PIN for enrolling but require one for auth

**Comment by tbbkitty** [comment]
I didn't read your response right.

For a Yubikey that dies not have a pin, like one configured in Firefox, authentik seems to have issues and sends the user in a lopp where they need to re-authenticate over and over with their Yubikey. However if the Yubikey was setup with anything but Firefox the default is that it will have a pin, and if it already does, everything works as expected.

This is only an issue if the Yubikey has no pin at all.

The settings for the for the stages are default. They just have a different name.

**Comment by tbbkitty** [comment]
![image](https://github.com/user-attachments/assets/9c769a00-cc15-4e49-84ff-0927598062aa)

**Comment by BeryJu** [comment]
I've just re-tested this with firefox on macos and fedora linux and both of them let me enroll a yubikey 5 without a pin but both of them also let me authenticate with the yubikey successfully. authentik-wise this is all default settings.

**Comment by RedL0tus** [comment]
I met the exact same issue with my Authentik instance. I'm running Authentik 2024.12.2 using Podman Quadlet on RHEL (basically docker-compose with a few twists). I had to manually create the passwordless sign in stage as my instance was upgraded from an older version.

**Comment by tbbkitty** [comment]
Seems like this issue was resolved in an earlier update so I am closing this.

**Comment by RedL0tus** [comment]
After upgrading to 2024.12.3, this issue persists on my instance. I tried to delete and re-add my pin-less WebAuthn device and it didn't solve the issue. I'm happy to help in case you need any more info.

**Comment by shibco** [comment]
I am encountering this issue. Probably not great for it to be closed!

**Comment by shibco** [comment]
We were testing Authentik at World Ethical Data Foundation, and have since determined this issue means that Authentik is not suitable for our identity management needs.

**Comment by melizeche** [comment]
@shibco if you read the thread the OP closed this issue because it was solved for them after an upgrade. 
If you're encountering a similar issue with the last version of authentik, that could be a bug and you're free to open a new issue/bug report and provide the necessary information to reproduce the bug
