### ISSUE TITLE
User gets 405 Method not allowed, when logging in using Okta SAML, while having an active session

### ISSUE THREAD

**Issue by adeptula7b** [goauthentik/authentik#12087]
**Describe the bug**
Referring yesterdays discussion with Jens. We have problem with Okta SAML connection. When user is already logged in into our application and tries to log in through Okta, he gets 405 Method Not Allowed from source/saml/.../acs and gets stuck on an empty page. If the user is not logged in, it's fine. We also see in logs:
```
IntegrityError('duplicate key value violates unique constraint \"authentik_core_usersourc_user_id_source_id_ad1f5aa7_uniq\"\\nDETAIL:  Key (user_id, source_id)=(1006, 52889114-3e77-49c7-9737-c3c3a39ff0c1) already exists.').
```
This started to occur after update from 2024.4 to 2024.8, and is still relevant in 2024.10.1

**To Reproduce**

1. Create Okta connection
2. Try to log in through okta
3. User gets logged in correctly
4. Without logging out, go again to okta, try to log in again
5. We get 405 error from source/saml/.../acs

Seems like the cause is in `authentik.core.sources.flow_manager`. In 2024.4 it used to have `new_connection.save()`
```
    def get_action(self, **kwargs) -> tuple[Action, UserSourceConnection | None]:  # noqa: PLR0911
        """decide which action should be taken"""
        new_connection = self.connection_type(source=self.source, identifier=self.identifier)
        # When request is authenticated, always link
        if self.request.user.is_authenticated:
            new_connection.user = self.request.user
            new_connection = self.update_connection(new_connection, **kwargs)

            new_connection.save()
``` 
which throw error on insert that was caught by:
```
    def get_flow(self, **kwargs) -> HttpResponse:
        """Get the flow response based on user_matching_mode"""
        try:
            action, connection = self.get_action(**kwargs)
        except IntegrityError as exc:
            self._logger.warning("failed to get action", exc=exc)
            return redirect(reverse("authentik_core:root-redirect"))
```
Now insert was moved further, hence there is no redirection.

**Expected behavior**
Instead of empty page we get redirected

**Screenshots**
![image](https://github.com/user-attachments/assets/de92ac28-06d5-4119-b008-682b46122467)

**Version and Deployment (please complete the following information):**

-   authentik version: 2024.10.1
-   Deployment: docker-compose, helm

**Additional context**

**Comment by BeryJu** [comment]
fixed by #12080, will be included in 2024.10.3

**Comment by saimonhowlader** [comment]
Confirming this bug is still present in **authentik 2026.2.2** — same `authentik_core_usersourc_user_id_source_id_ad1f5aa7_uniq` constraint violation, same root cause in `core/sources/flow_manager.py`. Reproducing with the **OAuth source path** (Google), not just SAML:

**Repro:**
1. Sign in to authentik as user X (any way — admin login, password, prior Google OAuth)
2. While still logged in as X, click an OAuth source button that's already linked to X
3. Google OAuth completes successfully → `/source/oauth/callback/google/` returns 500

**Stack trace (truncated to the relevant frames):**
```
File "/authentik/sources/oauth/views/callback.py", line 79, in dispatch
File "/authentik/core/sources/flow_manager.py", line 163, in get_flow
File "/authentik/core/sources/flow_manager.py", line 306, in handle_existing_link
File "django/db/models/base.py", line 902, in save
File "django/db/models/base.py", line 1058, in _save_parents
File "django/db/models/base.py", line 1169, in _save_table
File "django/db/models/base.py", line 1210, in _do_insert
django.db.utils.IntegrityError: duplicate key value violates unique constraint
  "authentik_core_usersourc_user_id_source_id_ad1f5aa7_uniq"
DETAIL: Key (user_id, source_id)=(4, d07b770e-...) already exists.
```

`handle_existing_link` is finding the existing `UserSourceConnection` (so it knows the link is there) but then calling `.save()` on what should be the existing object — Django's `_save_parents` triggers an INSERT on the parent class instead of an UPDATE, hitting the unique constraint.

**Workaround for users hitting this:** sign out (`/if/flow/default-invalidation-flow/`) before clicking the source button — anonymous OAuth re-link works correctly because there's no current user to attach to. The bug only triggers when the current authenticated user already has the source linked.

Happy to test a fix against 2026.2.x if anyone picks this up.
