### ISSUE TITLE
dashboard displays all outposts as not available with 2024.12.1

### ISSUE THREAD

**Issue by cheggerdev** [goauthentik/authentik#12487]
**Describe the bug**
The Dashboard displays all outposts as not available with 2024.12.1

**To Reproduce**

1. Go to 'Dashboard'
2. See outposts displays in blue meaning unavailable

**Expected behavior**
Outposts should be shown in green as they were with 2024.12.0

**Screenshots**
<img width="233" alt="Screenshot 2024-12-25 at 22 21 22" src="https://github.com/user-attachments/assets/730e6e31-bdf3-404d-886a-654fa98d79a5" />

**Logs**
Output of docker-compose logs or kubectl logs respectively

**Version and Deployment (please complete the following information):**

-   authentik version: 2024.12.1
-   Deployment: docker-compose

**Comment by cheggerdev** [comment]
Could this be fixed with pull request https://github.com/goauthentik/authentik/pull/12470 ?

**Comment by LeVraiRoiDHyrule** [comment]
I am having the exact same problem

**Comment by Harrdy** [comment]
I’m also experiencing the same issues. Outposts become unavailable with 2024.12, and 2024.12.1 doesn’t fix the problem.

**Comment by larsl-net** [comment]
I fixed my manual deployed outposts by using the `2024.12.0` image instead of `2024.12.1` and also added the in this version missing tailing `/` to the `AUTHENTIK_HOST` env var.

**Comment by luukrijnbende** [comment]
I'm experiencing the same issue, temporarily using version `2024.12.0` for the outpost and appending a `/` to the env var fixes it for now. The embedded outpost however, remains unavailable.

**Comment by larsl-net** [comment]
The problem got fixed with [#12470](https://github.com/goauthentik/authentik/pull/12470), as described in https://github.com/goauthentik/authentik/issues/12464#issuecomment-2561254874, until a new release is published you can fix it by using the dev images.

To fix the embedded outpost, change your authentik server image to `ghcr.io/goauthentik/dev-server:gh-version-2024.12`.

For manual deployed outpost, you need to change your image to `ghcr.io/goauthentik/dev-proxy:gh-version-2024.12`.
