### ISSUE TITLE
Custom CSS not injected in 2025.4 even with proper branding configuration

### ISSUE THREAD

**Issue by geoffreyjt** [goauthentik/authentik#14328]
---

Description :

Hello,

After upgrading Authentik from version 2025.2 to 2025.4, the custom CSS no longer loads, even though it is correctly configured and accessible. Everything was working perfectly before the update.

---

Steps to reproduce:

1. Mount a valid CSS file in the container:

services:
  server:
    volumes:
      - ./branding/custom.css:/web/dist/custom.css

2. Set the custom CSS URL in the admin interface under Branding > Interface:

/static/dist/custom.css

3. Restart the container with:

docker compose down
docker compose up -d

4. Visit the Authentik web UI.
Expected behavior: the CSS is applied (e.g., background color, modified text, etc.)

---

What happens:

The CSS file is correctly accessible at https://auth.mydomain/static/dist/custom.css

However, it is not injected as a <link rel="stylesheet"> in the page.

Instead, the string /web/dist/custom.css appears inside a <style> tag, which makes it invalid and has no effect.

Only the default CSS (/static/dist/authentik.css) is applied.

This used to work perfectly in version 2025.2.

---

Additional info:

Confirmed mounting path /web/dist/custom.css and corresponding URL /static/dist/custom.css are both valid and accessible.

The changelog for 2025.4 mentions:

> "brands: migrate custom CSS to brands"

This seems to have broken the actual injection of the custom stylesheet.

---

Expected behavior:

Custom CSS configured via the branding interface should be injected in the frontend <head> as:

<link rel="stylesheet" href="/static/dist/custom.css">

---

Let me know if you need further details or test files. Thanks!

**Comment by dominic-r** [comment]
Already fixed by https://github.com/goauthentik/authentik/pull/14306 which will be released in the next patch

**Comment by geoffreyjt** [comment]
Perfect, thanks for the information 👍

**Comment by Gaspa79** [comment]
#14306 does not fix this. I believe it targets the migration issue only. Anyway, even if you create everything from scratch, custom.css is still applied with <style> in 2025.4.1 . That has no effect since it should be a link, not a style.
