### ISSUE TITLE
Admin interface crashes in Safari

### ISSUE THREAD

**Issue by soundstorm** [goauthentik/authentik#14322]
Using authentik 2025.4.0 and Safari on macOS 15.3.1 the admin dashboard crashes with "repeated problem", Chrome on same machine works normal.

**Comment by GirlBossRush** [comment]
@soundstorm Thanks for reporting this. We've been steadily improving authentik's compatibility with Safari on a few fronts. 

The root cause of this bug (and other Safari-specific issues) is related to mutation observers on Web Component attributes triggering out-of-memory crashes. Additionally, our front-end's approach to style management can result in subtle UI issues that only manifest in Safari's rendering engine.

While Chromium browsers handle these edge cases more gracefully, Safari tends to implement web specifications more strictly. The good news is that both the [out-of-memory crash](https://github.com/goauthentik/authentik/pull/14181) and many of the [styling issues](https://github.com/goauthentik/authentik/pull/14392) should be resolved in our upcoming release.

Thanks again for letting us know about this issue and for your patience as we roll out the next release of authentik 🙏

**Comment by soundstorm** [comment]
Not picked for 2025.4.1, I'll check back on later release :)

**Comment by Samlant** [comment]
Just a small bump on this. Getting Page not found in Safari but works on Chromium-based browser as mentioned.

**Comment by BeryJu** [comment]
Fixed by https://github.com/goauthentik/authentik/pull/14181 in 2025.4

**Comment by Brandon4466** [comment]
Still an issue. `A problem repeatedly occurred with` only when trying to enter the Admin interface in Safari, on both macOS and iOS. Works fine with Firefox and Chrome. Interestingly, if I hit the back button when that message shows, it actually loads the Admin interface, but then once I click on anything else it immediately goes to that message and the back button doesn't fix it.
