### ISSUE TITLE
Web Certificate not being used

### ISSUE THREAD

**Issue by NielsDa** [goauthentik/authentik#18544]
### Describe the bug

It uses the default self signed certificate, instead of the assigned certificate.

I Name and paste the LetsEncrypt certificate and key into the System->Certificates>Import UI. (I have also tried the cmd line import with same result)
In System->Brand>Edit I change the selection from the selfsigned certificate, to the name given above.

When I connect via. https i get a security warning in my browser since it still gets the self-signed certificate.

If I delete the self-signed certificate in System->Certificates then I get the LetsEncrypt certificate as expected (i.e. no browser warning, and the certificate is a LetsEncrypt  cert).
If I restart the docker container, it generates a new selfsigned certificate, and used this for https.

So after every restart I have to accept the unsafe certificate in my browser, and then log in and delete the newly self-signed certificate. When the self-signed certificate have been deleted I get the correct valid certificate in my browser.

Question:
Are the Authentik running its own DNS resolver ? and trying to be "smart" about the certificate selection?
I'm running an split DNS on my domain, so the DNS lookup will give different IP depending if you ask the WAN side or the LAN side DNS. IP address of LAN side DNS is server is provided by DHCP,

 

### How to reproduce

1. I Name and paste the LetsEncrypt certificate and key into the System->Certificates>Import UI
2. In System->Brand>Edit I change the selection from the selfsigned certificate, to the name given above
3. The system uses the imported certificate for HTTPS.
4. Restart docker container
5. A self signed certificate is used for HTTPS.

### Expected behavior

1. I Name and paste the LetsEncrypt certificate and key into the System->Certificates>Import UI
2. In System->Brand>Edit I change the selection from the selfsigned certificate, to the name given above
3. The system uses the imported certificate for HTTPS.
4. Restart docker container
5. The system uses the imported certificate for HTTPS.

### Deployment Method

Docker

### Version

2025.10.0

### Relevant log output

```shell

```

**Comment by NielsDa** [comment]
This might be the same as this issue: https://github.com/goauthentik/authentik/issues/7173
The log in the web UI did not seem to contain information related to the certificate.
Since the issue is readily reproducible, please provide information for more detailed logging.

**Comment by dewi-tik** [comment]
Replicated this behavior. Restarting the server also applies the new cert without having to delete the default cert

**Comment by NielsDa** [comment]
Yes, but the only way to get it to use the correct certificate for HTTPS, is to delete the self-signed one.
This is undone when the server restarts.
I can see that it also generates a new self-signed certificate after some (up) time, but it seems like it is not applied for HTTPS unless the server restarts.

**Comment by dewi-tik** [comment]
This is fixed by the linked PR which should be included in 2025.12.2. Thanks for reporting.

**Comment by Salvora** [comment]
this issue still not fixed. please, reopen @dewi-tik 
2026.2.0 and I have the same problem.
Certificates auto discovered.
Set the brand to use the discovered certificate with matching domain.
compose down
compose up
still uses default certificate.

I use multidomain wildcard certificate
so may certificate covers *.foo.com and *.bar.com
I try to access the webui with auth.foo.com
uses the default self signed certificate.
