### ISSUE TITLE
Kubernetes: "event":"failed to proxy to backend"

### ISSUE THREAD

**Issue by replay111** [goauthentik/authentik#19080]
### Describe the bug

Deployment to k8s cluster ends with error:
```
│ {"error":"context canceled","event":"failed to proxy to backend","level":"warning","logger":"authentik.router","timestamp":"2025-12-28T14:32:37Z"}                                                                                            │
│ {"auth_via": "unauthenticated", "domain_url": "10.0.0.78", "event": "/-/health/ready/", "host": "10.0.0.78:9000", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 48, "remote": "10.0.0.35", "request_id": "4bfc26d8ebcf │
│ 457ab3d270c8389b63b4", "runtime": 6025, "schema_name": "public", "scheme": "http", "status": 200, "timestamp": "2025-12-28T14:32:47.028682", "user": "", "user_agent": "kube-probe/1.34"}                                                     │
│ {"error":"context canceled","event":"failed to proxy to backend","level":"warning","logger":"authentik.router","timestamp":"2025-12-28T14:32:47Z"}                                                                                            │
│ {"auth_via": "unauthenticated", "domain_url": "10.0.0.78", "event": "/-/health/ready/", "host": "10.0.0.78:9000", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 48, "remote": "10.0.0.35", "request_id": "d94d882bb55d │
│ 42dfb237c30053e38749", "runtime": 6025, "schema_name": "public", "scheme": "http", "status": 200, "timestamp": "2025-12-28T14:32:57.029301", "user": "", "user_agent": "kube-probe/1.34"}                                                     │
│ {"error":"context canceled","event":"failed to proxy to backend","level":"warning","logger":"authentik.router","timestamp":"2025-12-28T14:32:57Z"}  
```

Portal is available for ~20sec and then pod is marked as failed....

### How to reproduce

1. values:
```
authentik:
  secret_key: "xxxx"
  log_level: info

  error_reporting:
    enabled: false

  disable_update_check: true
  disable_startup_analytics: true    

  postgresql:
    host: "postgresql-svc.postgresql-18.svc.cluster.local"
    name: "authentik"
    user: "authentik"
    password: "authentik"
    port: 5432

server:
  ingress:
    enabled: true
    https: false

    ingressClassName: nginx
    annotations:
      # SSL configuration
      nginx.ingress.kubernetes.io/ssl-redirect: 'true'
      nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
      nginx.ingress.kubernetes.io/proxy-ssl-verify: "off"

      # Backend protocol
      nginx.ingress.kubernetes.io/backend-protocol: 'HTTP'

      # WebSocket specific timeouts
      nginx.ingress.kubernetes.io/proxy-read-timeout: '3600'
      nginx.ingress.kubernetes.io/proxy-send-timeout: '3600'
      nginx.ingress.kubernetes.io/proxy-connect-timeout: '3600'    
      
      # Cert Manager Certificate 
      cert-manager.io/cluster-issuer: "cm-vault-issuer"
      cert-manager.io/private-key-size: "4096"
      cert-manager.io/renew-before: "12h"
      cert-manager.io/revision-history-limit: "1"
      cert-manager.io/duration: "720h"
    tls:
      - secretName: authentik-tls
        hosts:
          - authentik.k8s.domain

    hosts:
      - authentik.k8s.domain

 
postgresql:
  enabled: false

```
2. Helmchart:
```
helm repo add authentik https://charts.goauthentik.io
helm repo update
helm search repo authentik --versions | head -n 5

helm template authentik-idm authentik/authentik --namespace authentik-idm --version 2025.10.3 -f values.yaml --debug > authentik_2025.10.3.yaml


kubectl create namespace authentik-idm || echo "Already exist"
kubectl apply -f authentik_2025.10.3.yaml -n authentik-idm
```

### Expected behavior

expected behavior: normal access to portal and be able to configure service.

### Additional context

Postgresql 18.1 - it is launched in separate namespace for k8s cluster - authentik has access and was able to run all migrations.

### Deployment Method

Kubernetes

### Version

v1.34.2

### Relevant log output

```shell
│ {"auth_via": "unauthenticated", "domain_url": "10.0.0.78", "event": "/-/health/ready/", "host": "10.0.0.78:9000", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 48, "remote": "10.0.0.35", "request_id": "621ecdc19902 │
│ 40e29b4639d0ac2f0fbd", "runtime": 6025, "schema_name": "public", "scheme": "http", "status": 200, "timestamp": "2025-12-28T14:31:50.030909", "user": "", "user_agent": "kube-probe/1.34"}                                                     │
│ {"error":"context canceled","event":"failed to proxy to backend","level":"warning","logger":"authentik.router","timestamp":"2025-12-28T14:31:50Z"}                                                                                            │
│ {"event":"updating brand certificates","level":"info","logger":"authentik.router.brand_tls","timestamp":"2025-12-28T14:31:52Z"}                                                                                                               │
│ {"error":"context canceled","event":"failed to proxy to backend","level":"warning","logger":"authentik.router","timestamp":"2025-12-28T14:32:00Z"}                                                                                            │
│ {"auth_via": "ipc", "domain_url": "0.0.0.0", "event": "/api/v3/core/brands/?page=1&page_size=100", "host": "0.0.0.0:9000", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 48, "remote": "127.0.0.1", "request_id": "a89 │
│ d0a032fa84b70873b67d99e3baea4", "runtime": 23, "schema_name": "public", "scheme": "http", "status": 200, "timestamp": "2025-12-28T14:32:03.711470", "user": "authentik:system", "user_agent": "goauthentik.io/ipc/2025.10.3"}                 │
│ {"auth_via": "unauthenticated", "domain_url": "10.0.0.78", "event": "/-/health/ready/", "host": "10.0.0.78:9000", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 48, "remote": "10.0.0.35", "request_id": "71f2efa080e2 │
│ 4a7792589f385104684e", "runtime": 6026, "schema_name": "public", "scheme": "http", "status": 200, "timestamp": "2025-12-28T14:32:05.035026", "user": "", "user_agent": "kube-probe/1.34"}                                                     │
│ {"auth_via": "unauthenticated", "domain_url": "10.0.0.78", "event": "/-/health/ready/", "host": "10.0.0.78:9000", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 49, "remote": "10.0.0.35", "request_id": "d77b05a1089b │
│ 4cba8f8d474a8623fa07", "runtime": 6026, "schema_name": "public", "scheme": "http", "status": 200, "timestamp": "2025-12-28T14:32:10.033240", "user": "", "user_agent": "kube-probe/1.34"}                                                     │
│ {"error":"context canceled","event":"failed to proxy to backend","level":"warning","logger":"authentik.router","timestamp":"2025-12-28T14:32:10Z"}                                                                                            │
│ {"auth_via": "unauthenticated", "domain_url": "10.0.0.78", "event": "/-/health/ready/", "host": "10.0.0.78:9000", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 48, "remote": "10.0.0.35", "request_id": "17a25914a01a │
│ 4986b99a472c703627a6", "runtime": 6025, "schema_name": "public", "scheme": "http", "status": 200, "timestamp": "2025-12-28T14:32:20.030207", "user": "", "user_agent": "kube-probe/1.34"}                                                     │
│ {"error":"context canceled","event":"failed to proxy to backend","level":"warning","logger":"authentik.router","timestamp":"2025-12-28T14:32:20Z"}                                                                                            │
│ {"error":"context canceled","event":"failed to proxy to backend","level":"warning","logger":"authentik.router","timestamp":"2025-12-28T14:32:27Z"}                                                                                            │
│ {"auth_via": "unauthenticated", "domain_url": "10.0.0.78", "event": "/-/health/ready/", "host": "10.0.0.78:9000", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 49, "remote": "10.0.0.35", "request_id": "2e9089142669 │
│ 40569d55b6d31e8b6f46", "runtime": 6026, "schema_name": "public", "scheme": "http", "status": 200, "timestamp": "2025-12-28T14:32:35.034251", "user": "", "user_agent": "kube-probe/1.34"}                                                     │
│ {"auth_via": "unauthenticated", "domain_url": "10.0.0.78", "event": "/-/health/ready/", "host": "10.0.0.78:9000", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 48, "remote": "10.0.0.35", "request_id": "605d272c4650 │
│ 46178d7db698faf8a093", "runtime": 6028, "schema_name": "public", "scheme": "http", "status": 200, "timestamp": "2025-12-28T14:32:37.036525", "user": "", "user_agent": "kube-probe/1.34"}                                                     │
│ {"error":"context canceled","event":"failed to proxy to backend","level":"warning","logger":"authentik.router","timestamp":"2025-12-28T14:32:37Z"}                                                                                            │
│ {"auth_via": "unauthenticated", "domain_url": "10.0.0.78", "event": "/-/health/ready/", "host": "10.0.0.78:9000", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 48, "remote": "10.0.0.35", "request_id": "4bfc26d8ebcf │
│ 457ab3d270c8389b63b4", "runtime": 6025, "schema_name": "public", "scheme": "http", "status": 200, "timestamp": "2025-12-28T14:32:47.028682", "user": "", "user_agent": "kube-probe/1.34"}                                                     │
│ {"error":"context canceled","event":"failed to proxy to backend","level":"warning","logger":"authentik.router","timestamp":"2025-12-28T14:32:47Z"}                                                                                            │
│ {"auth_via": "unauthenticated", "domain_url": "10.0.0.78", "event": "/-/health/ready/", "host": "10.0.0.78:9000", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 48, "remote": "10.0.0.35", "request_id": "d94d882bb55d │
│ 42dfb237c30053e38749", "runtime": 6025, "schema_name": "public", "scheme": "http", "status": 200, "timestamp": "2025-12-28T14:32:57.029301", "user": "", "user_agent": "kube-probe/1.34"}                                                     │
│ {"error":"context canceled","event":"failed to proxy to backend","level":"warning","logger":"authentik.router","timestamp":"2025-12-28T14:32:57Z"}
```

**Comment by rissson** [comment]
Anything in `dmesg`, like python being killed for some reason?

**Comment by replay111** [comment]
I am trying to start it on kubernetes cluster co I can see logs from it - and it looks like this:

```
{"event":"using PostgreSQL session backend","level":"info","logger":"authentik.outpost.proxyv2","timestamp":"2026-01-06T18:06:23Z"}           
{"error":"context canceled","event":"failed to proxy to backend","level":"warning","logger":"authentik.router","timestamp":"2026-01-06T18:06:38Z"}                                                                                                                                       
{"auth_via": "secret_key", "domain_url": "0.0.0.0", "event": "/api/v3/outposts/proxy/?page=1&page_size=100", "host": "0.0.0.0:9000", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 48, "remote": "127.0.0.1", "request_id": "b909f28f4cc14500ba5fb9049aecd495", " 
{"event":"No providers assigned to this outpost, check outpost configuration in authentik","level":"warning","logger":"authentik.outpost.proxyv2","timestamp":"2026-01-06T18:06:40Z"}                                                                                                    
{"event":"updating brand certificates","level":"info","logger":"authentik.router.brand_tls","timestamp":"2026-01-06T18:06:40Z"}                                                                                                                                                          
{"auth_via": "secret_key", "domain_url": null, "event": "runtime error during accept", "exc": "RuntimeError(\"Expected ASGI message 'websocket.send' or 'websocket.close', but got 'websocket.accept'.\")", "level": "warning", "logger": "authentik.outposts.consumer", "outpost": "<Ou 
{"auth_via": "secret_key", "domain_url": null, "event": "Exception in ASGI application", "exc": "ClientDisconnected()", "level": "warning", "logger": "authentik.asgi", "pid": 48, "schema_name": "public", "timestamp": "2026-01-06T18:06:42.410307"}                                   
Exception in ASGI application                                                                                                                                                                                                                                                            
Traceback (most recent call last):                                                                                                                                                                                                                                                       
   File "/ak-root/.venv/lib/python3.13/site-packages/uvicorn/protocols/websockets/wsproto_impl.py", line 235, in run_asgi                                                                                                                                                                  
     result = await self.app(self.scope, self.receive, self.send)  # type: ignore[func-returns-value]                                                                                                                                                                                      
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                                                                          
   File "/ak-root/.venv/lib/python3.13/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__                                                                                                                                                                            
     return await self.app(scope, receive, send)                                                                                                                                                                                                                                           
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                                                                                           
   File "/ak-root/.venv/lib/python3.13/site-packages/sentry_sdk/integrations/asgi.py", line 174, in _run_asgi3                                                                                                                                                                             
     return await self._run_app(scope, receive, send, asgi_version=3)                                                                                                                                                                                                                      
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                                                                      
   File "/ak-root/.venv/lib/python3.13/site-packages/sentry_sdk/integrations/asgi.py", line 276, in _run_app                                                                                                                                                                               
     raise exc from None                                                                                                                                                                                                                                                                   
   File "/ak-root/.venv/lib/python3.13/site-packages/sentry_sdk/integrations/asgi.py", line 271, in _run_app                                                                                                                                                                               
     return await self.app(                                                                                                                                                                                                                                                                
            ^^^^^^^^^^^^^^^                                                                                                                                                                                                                                                                
         scope, receive, _sentry_wrapped_send                                                                                                                                                                                                                                              
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                                                                                              
     )                                                                                                                                                                                                                                                                                     
     ^                                                                                                                                                                                                                                                                                     
   File "/ak-root/.venv/lib/python3.13/site-packages/channels/routing.py", line 48, in __call__                                                                                                                                                                                            
     return await application(scope, receive, send)                                                                                                                                                                                                                                        
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                                                                                        
   File "/authentik/root/asgi.py", line 56, in __call__                                                                                                                                                                                                                                    
     return await self.app(scope, receive, send)                                                                                                                                                                                                                                           
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                                                                                           
   File "/ak-root/.venv/lib/python3.13/site-packages/channels/routing.py", line 118, in __call__                                                                                                                                                                                           
     return await application(                                                                                                                                                                                                                                                             
            ^^^^^^^^^^^^^^^^^^                                                                                                                                                                                                                                                             
     ...<10 lines>...                                                                                                                                                                                                                                                                      
     )                                                                                                                                                                                                                                                                                     
     ^                                                                                                                                                                                                                                                                                     
   File "/ak-root/.venv/lib/python3.13/site-packages/channels/routing.py", line 118, in __call__                                                                                                                                                                                           
     return await application(                                                                                                                                                                                                                                                             
            ^^^^^^^^^^^^^^^^^^                                                                                                                                                                                                                                                             
     ...<10 lines>...                                                                                                                                                                                                                                                                      
     )                                                                                                                                                                                                                                                                                     
     ^                                                                                                                                                                                                                                                                                     
   File "/authentik/root/middleware.py", line 298, in __call__                                                                                                                                                                                                                             
     return await send({"type": "websocket.close"})                                                                                                                                                                                                                                        
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                                                                                        
   File "/ak-root/.venv/lib/python3.13/site-packages/sentry_sdk/integrations/asgi.py", line 264, in _sentry_wrapped_send                                                                                                                                                                   
     return await send(event)                                                                                                                                                                                                                                                              
            ^^^^^^^^^^^^^^^^^                                                                                                                                                                                                                                                              
   File "/ak-root/.venv/lib/python3.13/site-packages/uvicorn/protocols/websockets/wsproto_impl.py", line 370, in send                                                                                                                                                                      
     raise RuntimeError(msg % message_type)                                                                                                                                                                                                                                                
 RuntimeError: Unexpected ASGI message 'websocket.close', after sending 'websocket.close'.                                                                                                                                                                                                 
 {"auth_via": "unauthenticated", "domain_url": "10.0.0.172", "event": "/-/health/ready/", "host": "10.0.0.172:9000", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 47, "remote": "10.0.0.35", "request_id": "7b21dd08ada64723b50397c023f3ff45", "runtime": 6028, "  
 {"error":"read tcp 127.0.0.1:34796->127.0.0.1:9000: i/o timeout","event":"failed to connect websocket","level":"warning","logger":"authentik.outpost.ak-api-controller","timestamp":"2026-01-06T18:06:44Z"}                                                                               
 {"event":"waiting 1 seconds to reconnect","level":"info","logger":"authentik.outpost.ak-api-controller","timestamp":"2026-01-06T18:06:44Z"}                                                                                                                                               
 {"error":"context canceled","event":"failed to proxy to backend","level":"warning","logger":"authentik.router","timestamp":"2026-01-06T18:06:44Z"} 
 RuntimeError: Unexpected ASGI message 'websocket.close', after sending 'websocket.close'.                                                                                                                                                                                                 
 {"auth_via": "unauthenticated", "domain_url": "10.0.0.172", "event": "/-/health/ready/", "host": "10.0.0.172:9000", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 47, "remote": "10.0.0.35", "request_id": "7b21dd08ada64723b50397c023f3ff45", "runtime": 6028, "  
 {"error":"read tcp 127.0.0.1:34796->127.0.0.1:9000: i/o timeout","event":"failed to connect websocket","level":"warning","logger":"authentik.outpost.ak-api-controller","timestamp":"2026-01-06T18:06:44Z"}  

```
looks like websocket problem - I added extra annotations to nginx ingress:

```
      # Backend protocol
      nginx.ingress.kubernetes.io/backend-protocol: 'HTTP'

      # WebSocket specific timeouts
      nginx.ingress.kubernetes.io/proxy-read-timeout: '3600'
      nginx.ingress.kubernetes.io/proxy-send-timeout: '3600'
      nginx.ingress.kubernetes.io/proxy-connect-timeout: '3600'    

      # Buffering settings
      # nginx.ingress.kubernetes.io/proxy-buffering: 'off'
      # nginx.ingress.kubernetes.io/proxy-request-buffering: 'off'
      
      # WebSocket headers (usually auto-detected)
      nginx.ingress.kubernetes.io/upstream-hash-by: '$remote_addr'

      # Session affinity for WebSocket
      nginx.ingress.kubernetes.io/affinity: 'cookie'
      nginx.ingress.kubernetes.io/affinity-mode: 'persistent'
      nginx.ingress.kubernetes.io/session-cookie-name: 'ws-server'
      nginx.ingress.kubernetes.io/session-cookie-expires: '86400'
      nginx.ingress.kubernetes.io/session-cookie-max-age: '86400'
      nginx.ingress.kubernetes.io/session-cookie-path: '/'

      # Rate limiting
      # nginx.ingress.kubernetes.io/limit-rps: '10'
      # nginx.ingress.kubernetes.io/limit-connections: '100'
  
      # CORS settings
      nginx.ingress.kubernetes.io/enable-cors: 'true'
      nginx.ingress.kubernetes.io/cors-allow-origin: '*'
      nginx.ingress.kubernetes.io/cors-allow-methods: 'GET, PUT, POST, DELETE, PATCH, OPTIONS'
      nginx.ingress.kubernetes.io/cors-allow-headers: 'DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization'
      nginx.ingress.kubernetes.io/cors-max-age: '1728000'      

      # Important: preserve host header      
      nginx.ingress.kubernetes.io/upstream-vhost: authentik.k8s.remote.dom.net
```

but it does not solve issue :/

**Comment by maetthu** [comment]
I just had a similar issue resulting in the same error (`failed to proxy to backend`) when upgrading from 2025.8.4 to 2025.10.3. The python exception was different though (`"DuplicatePreparedStatement('prepared statement \"_pg3_0\" already exists')"`), but maybe something like this appears in your logs as well.

What solved/mitigated it for me is to access the database directly, not through pgbouncer.

Another thing I noticed while reading through your report is that metrics are disabled by default in the helm chart. Maybe enabling it helps.

```
  worker:
    metrics:
      enabled: true

```

**Comment by replay111** [comment]
Hi,
regarding access to PostgreSQL - I am not using pgBouncer or any other "proxies" - it is just simple access to PG. I have another application and it has access to it, also I run pgAdmin4 on cluster and I am able to connect to db and manage it... also Authentik during start creates all necessary tables without a problem. 

Regarding metrics - worker seems to be runing fine - it populates db structure and its readiness k9s shows that all is fine - logs are from server part - which is not able to start.
I added worker block as you suggested but it did not change anything.... 

This clearly looks like some communication problems with websockets but I have no idea why... 
I just redeployed it once again without ingress - same issue (I just wanted to be sure that this is not caused by some tries to reach websocket through ingress setup).

**Comment by joelMuehlena** [comment]
Hi, I have the exact same issue. Also on `2025.10.3` before everything ran fine.

Edit: I downgraded to `2025.10.2` and it works again.
Edit2: Today it stopped working again (1day later)

**Comment by replay111** [comment]
@joelMuehlena I downgraded to version mentioned by you, but still apart additional container (redis) - authentik did not start correctly with error:

```
{"domain_url": null, "event": "Task enqueued", "level": "info", "logger": "authentik.tasks.middleware", "pid": 48, "schema_name": "public", "task_id": "56a9ab66-beee-453b-8e68-97060b9cc032", "task_name": "authentik.blueprints.v1.tasks.blueprints_discovery", "timestamp": "2026-01-14T21:30:33.400926"}
{"domain_url": null, "event": "Task enqueued", "level": "info", "logger": "authentik.tasks.middleware", "pid": 48, "schema_name": "public", "task_id": "bf8cef45-207f-43ec-b66e-825145ab5cee", "task_name": "authentik.blueprints.v1.tasks.clear_failed_blueprints", "timestamp": "2026-01-14T21:30:33.418856"}
{"domain_url": null, "event": "authentik Core Worker finished starting", "level": "info", "logger": "authentik.root.signals", "pid": 48, "schema_name": "public", "timestamp": "2026-01-14T21:30:33.475998", "took_s": 7.208835}
{"auth_via": "ipc", "domain_url": "0.0.0.0", "event": "/api/v3/core/brands/?page=1&page_size=100", "host": "0.0.0.0:9000", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 49, "remote": "127.0.0.1", "request_id": "71ac7fa8bfbe47bf8a083ffcbd8acff7", "runtime": 86, "schema_name": "public", "scheme": "http", "status": 200, "timestamp": "2026-01-14T21:30:38.924699", "user": "authentik:system", "user_agent": "goauthentik.io/ipc/2025.10.2"}
{"auth_via": "secret_key", "domain_url": "0.0.0.0", "event": "/api/v3/outposts/instances/", "host": "0.0.0.0:9000", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 49, "remote": "127.0.0.1", "request_id": "399abd29a6c44052877bd3f9ae228f64", "runtime": 122, "schema_name": "public", "scheme": "http", "status": 200, "timestamp": "2026-01-14T21:30:38.953068", "user": "ak-outpost-8d6a8fde5b0e46b5b18ece785b763772", "user_agent": "goauthentik.io/outpost/2025.10.2"}
{"error":"context canceled","event":"failed to proxy to backend","level":"warning","logger":"authentik.router","timestamp":"2026-01-14T21:30:42Z"}
{"auth_via": "secret_key", "domain_url": "0.0.0.0", "event": "/api/v3/root/config/", "host": "0.0.0.0:9000", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 49, "remote": "127.0.0.1", "request_id": "90e43389679442c49ac7f840ec99557a", "runtime": 35, "schema_name": "public", "scheme": "http", "status": 200, "timestamp": "2026-01-14T21:30:45.039022", "user": "ak-outpost-8d6a8fde5b0e46b5b18ece785b763772", "user_agent": "goauthentik.io/outpost/2025.10.2"}
{"embedded":true,"event":"Outpost mode","level":"info","logger":"authentik.outpost.ak-api-controller","timestamp":"2026-01-14T21:30:45Z"}
```

so - the same issue :/

**Comment by joelMuehlena** [comment]
So today, I 
- upgraded my Talos Cluster from 1.11.5 to 1.12.1
- upgraded K8s from 1.34.2 to 1.35
- upgraded authentik to 2025.12.1

and thus rebooted all VMs. I also fixed some other bugs in the cluster which caused strange effects over the last few weeks but I first discovered today. Sincen then (only a few hours now but longer than before) it seems to work again. In detail there were some issues with CoreDNS and the Cluster Pod/Service CIDRs.

The `failed to proxy to backend` log entry is gone as well as the restarts and not ready pods which had issues with live and readiness probes.

**Comment by replay111** [comment]
@joelMuehlena so I presume this issue is somehow related with kubernetes version...? I cant upgrade it yet so I am using 1.34.2, but I redeployed authentik with 2025.12.1 chart and issue is still the same.

**Comment by joelMuehlena** [comment]
Actually I think it was a combination of infrastructure & cluster failure which led to errors in rare cases. But was hard to spot because only some of the services in my cluster were not working as they should in some cases.

**Comment by replay111** [comment]
On the cluster I am doing tests with authentik - authentik is the only service that has problems :/ The rest is working fine...
