### ISSUE TITLE
Duo MFA 404 on "check status"

### ISSUE THREAD

**Issue by DaveB91** [goauthentik/authentik#3288]
Brand new install of Authentik using docker.
Configured the Duo setup as per the docs
Can confirm the user and phones are being enrolled in the Duo platform
However clicking the "check status" button continually produces a 404 error, and cannot get past this poin
![Screen Shot 2022-07-20 at 4 33 41 pm](https://user-images.githubusercontent.com/4986691/179913439-ee08cd10-9412-479b-9b20-f3b40d31958b.png)
t

**Comment by los93sol** [comment]
I'm having the same issue here.  I got one account to work somehow, but can't setup any others, wondering if it's somehow related to multiple accounts being tied to one device.

**Comment by DaveB91** [comment]
Any tips on how you got the one to work? I have been banging my head against the wall for weeks on this.

**Comment by BeryJu** [comment]
Which reverse proxy are you using? @los93sol @DaveB91 The issue should be fixed with the commit above, and there's currently also another error that happens when the enrollment finishes (the device is still created correctly), that the above commit also fixes

**Comment by DaveB91** [comment]
> Which reverse proxy are you using? @los93sol @DaveB91 The issue should be fixed with the commit above, and there's currently also another error that happens when the enrollment finishes (the device is still created correctly), that the above commit also fixes

I am still having the issue even after updating go the latest version released today
Reverse proxy is CloudFlare, however it also doesn't work when I remove the reverse proxy from the mix

**Comment by BeryJu** [comment]
Hmm, could you check the authentik server logs when opening the duo enrollment flow?

**Comment by DaveB91** [comment]
Nothing more then just me logging in - No logs when I try to enrol Duo.
Worth noting that it is creating the user in Duo.
<img width="1552" alt="Screen Shot 2022-08-18 at 1 03 34 pm" src="https://user-images.githubusercontent.com/4986691/185284006-689ed064-56aa-4899-8c0a-5f1d9e5356ec.png">

**Comment by los93sol** [comment]
I confirm the same issue happens here.  Dev tools seems to indicate that the request to check the enrollment status is looping back to Authentik and not going to Duo as I’d expect.

**Comment by los93sol** [comment]
> Which reverse proxy are you using? @los93sol @DaveB91 The issue should be fixed with the commit above, and there's currently also another error that happens when the enrollment finishes (the device is still created correctly), that the above commit also fixes

I have an nginx proxy in front of Authentik.

**Comment by luukrijnbende** [comment]
I'm experiencing the same issue, though my Authentik instance is not yet exposed to the internet.

**Comment by BeryJu** [comment]
my bad @DaveB91 I meant the server container logs, @los93sol and @luukrijnbende could you also post the server container logs (ideally with the log level set to debug)

**Comment by luukrijnbende** [comment]
@BeryJu I've set the log level to debug and tried to re-enroll Duo, see log below.
The user is created is created in Duo, but the enrollment_status gives a 404.

```
{"auth_via": "session", "event": "f(plan): starting planning process", "flow_slug": "default-authenticator-duo-setup", "host": "REDACTED", "level": "debug", "logger": "authentik.flows.planner", "pid": 22, "request_id": "750226c268454d6b910ab8c72a64a30d", "timestamp": "2022-09-11T14:32:52.902115"}
{"auth_via": "session", "event": "f(plan): building plan", "flow_slug": "default-authenticator-duo-setup", "host": "REDACTED", "level": "debug", "logger": "authentik.flows.planner", "pid": 22, "request_id": "750226c268454d6b910ab8c72a64a30d", "timestamp": "2022-09-11T14:32:52.904846"}
{"auth_via": "session", "event": "f(plan): evaluating on plan", "flow_slug": "default-authenticator-duo-setup", "host": "REDACTED", "level": "debug", "logger": "authentik.flows.planner", "pid": 22, "request_id": "750226c268454d6b910ab8c72a64a30d", "stage": "<AuthenticatorDuoStage: Duo Authenticator Setup Stage duo-authenticator-stage>", "timestamp": "2022-09-11T14:32:52.916543"}
{"auth_via": "session", "event": "f(plan): stage passing", "flow_slug": "default-authenticator-duo-setup", "host": "REDACTED", "level": "debug", "logger": "authentik.flows.planner", "pid": 22, "request_id": "750226c268454d6b910ab8c72a64a30d", "stage": "<AuthenticatorDuoStage: Duo Authenticator Setup Stage duo-authenticator-stage>", "timestamp": "2022-09-11T14:32:52.918012"}
{"auth_via": "session", "event": "f(plan): finished building", "flow_slug": "default-authenticator-duo-setup", "host": "REDACTED", "level": "debug", "logger": "authentik.flows.planner", "pid": 22, "request_id": "750226c268454d6b910ab8c72a64a30d", "timestamp": "2022-09-11T14:32:52.918210"}
{"auth_via": "session", "event": "/flows/-/configure/37c15022-1ee2-49e0-a055-ef165648e0c6/?next=%2Fif%2Fuser%2F%23%2Fsettings%3B%7B%22page%22%3A%22page-mfa%22%7D", "host": "REDACTED", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 22, "remote": "192.168.36.17", "request_id": "750226c268454d6b910ab8c72a64a30d", "runtime": 69, "scheme": "https", "status": 302, "timestamp": "2022-09-11T14:32:52.946913", "user": "luukrijnbende", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"}
{"auth_via": "session", "event": "/if/flow/default-authenticator-duo-setup/?next=%2Fif%2Fuser%2F%23%2Fsettings%3B%7B%22page%22%3A%22page-mfa%22%7D", "host": "REDACTED", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 22, "remote": "192.168.36.17", "request_id": "582d2e9a069748ae82121688c56d7759", "runtime": 23, "scheme": "https", "status": 200, "timestamp": "2022-09-11T14:32:52.976785", "user": "luukrijnbende", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"}
{"event":"/static/dist/assets/images/flow_background.jpg","host":"REDACTED","level":"info","logger":"authentik.router","method":"GET","remote":"192.168.36.17","runtime":"26.654","scheme":"https","size":594426,"status":200,"timestamp":"2022-09-11T14:32:53Z","upstream":"","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"}
{"auth_via": "session", "event": "f(exec): Continuing existing plan", "flow_slug": "default-authenticator-duo-setup", "host": "REDACTED", "level": "debug", "logger": "authentik.flows.views.executor", "pid": 22, "request_id": "27a8e777574c437fa4ccff22f5d6e24e", "timestamp": "2022-09-11T14:32:53.098911"}
{"auth_via": "session", "current_stage": "<AuthenticatorDuoStage: Duo Authenticator Setup Stage duo-authenticator-stage>", "event": "f(exec): Current stage", "flow_slug": "default-authenticator-duo-setup", "host": "REDACTED", "level": "debug", "logger": "authentik.flows.views.executor", "pid": 22, "request_id": "27a8e777574c437fa4ccff22f5d6e24e", "timestamp": "2022-09-11T14:32:53.099113"}
{"auth_via": "session", "event": "f(exec): Passing GET", "flow_slug": "default-authenticator-duo-setup", "host": "REDACTED", "level": "debug", "logger": "authentik.flows.views.executor", "pid": 22, "request_id": "27a8e777574c437fa4ccff22f5d6e24e", "stage": "<AuthenticatorDuoStage: Duo Authenticator Setup Stage duo-authenticator-stage>", "timestamp": "2022-09-11T14:32:53.099489", "view_class": "authentik.stages.authenticator_duo.stage.AuthenticatorDuoStageView"}
{"auth_via": "session", "event": "/api/v3/flows/executor/default-authenticator-duo-setup/?query=next%3D%252Fif%252Fuser%252F%2523%252Fsettings%253B%257B%2522page%2522%253A%2522page-mfa%2522%257D", "host": "REDACTED", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 22, "remote": "192.168.36.17", "request_id": "27a8e777574c437fa4ccff22f5d6e24e", "runtime": 276, "scheme": "https", "status": 200, "timestamp": "2022-09-11T14:32:53.361008", "user": "luukrijnbende", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"}
{"event":"/static/dist/flow/AuthenticatorDuoStage-bc0f3de1.js","host":"REDACTED","level":"info","logger":"authentik.router","method":"GET","remote":"192.168.36.17","runtime":"0.819","scheme":"https","size":11039,"status":200,"timestamp":"2022-09-11T14:32:53Z","upstream":"","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"}
{"auth_via": "session", "event": "/api/v3/stages/authenticator/duo/37c15022-1ee2-49e0-a055-ef165648e0c6/enrollment_status/", "host": "REDACTED", "level": "info", "logger": "authentik.asgi", "method": "POST", "pid": 22, "remote": "192.168.36.17", "request_id": "8fea0fa2e49d430fa12b666f330e95e9", "runtime": 20, "scheme": "https", "status": 404, "timestamp": "2022-09-11T14:32:56.415372", "user": "luukrijnbende", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"}
{"event": "Not Found: /api/v3/stages/authenticator/duo/37c15022-1ee2-49e0-a055-ef165648e0c6/enrollment_status/", "level": "warning", "logger": "django.request", "timestamp": 1662906776.4178116}
{"auth_via": "unauthenticated", "event": "/-/health/live/", "host": "localhost:8000", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 22, "remote": "127.0.0.1", "request_id": "d12abfdfaed04ea5801363022f4d4ecd", "runtime": 7, "scheme": "http", "status": 204, "timestamp": "2022-09-11T14:32:59.316226", "user": "", "user_agent": "goauthentik.io/proxy/healthcheck"}
{"auth_via": "session", "event": "/api/v3/stages/authenticator/duo/37c15022-1ee2-49e0-a055-ef165648e0c6/enrollment_status/", "host": "REDACTED", "level": "info", "logger": "authentik.asgi", "method": "POST", "pid": 22, "remote": "192.168.36.17", "request_id": "e6e5980b07dc4e1aa01d707b3f524c8d", "runtime": 18, "scheme": "https", "status": 404, "timestamp": "2022-09-11T14:32:59.410703", "user": "luukrijnbende", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"}
{"event": "Not Found: /api/v3/stages/authenticator/duo/37c15022-1ee2-49e0-a055-ef165648e0c6/enrollment_status/", "level": "warning", "logger": "django.request", "timestamp": 1662906779.4110758}
{"auth_via": "unauthenticated", "event": "/-/health/ready/", "host": "10.42.1.70:9000", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 22, "remote": "10.42.1.1", "request_id": "f4d7aace6bc545e6a24fc3978f48c509", "runtime": 10, "scheme": "http", "status": 204, "timestamp": "2022-09-11T14:33:01.891674", "user": "", "user_agent": "kube-probe/1.20"}
{"auth_via": "session", "event": "/api/v3/stages/authenticator/duo/37c15022-1ee2-49e0-a055-ef165648e0c6/enrollment_status/", "host": "REDACTED", "level": "info", "logger": "authentik.asgi", "method": "POST", "pid": 22, "remote": "192.168.36.17", "request_id": "90fd65e44f4b40f3a271c9188bed8ce0", "runtime": 19, "scheme": "https", "status": 404, "timestamp": "2022-09-11T14:33:02.409144", "user": "luukrijnbende", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"}
{"event": "Not Found: /api/v3/stages/authenticator/duo/37c15022-1ee2-49e0-a055-ef165648e0c6/enrollment_status/", "level": "warning", "logger": "django.request", "timestamp": 1662906782.4094765}
{"auth_via": "session", "event": "/api/v3/stages/authenticator/duo/37c15022-1ee2-49e0-a055-ef165648e0c6/enrollment_status/", "host": "REDACTED", "level": "info", "logger": "authentik.asgi", "method": "POST", "pid": 21, "remote": "192.168.36.17", "request_id": "5dd486e52bef4ebdada92304842b44a3", "runtime": 79, "scheme": "https", "status": 404, "timestamp": "2022-09-11T14:33:05.465648", "user": "luukrijnbende", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"}
{"event": "Not Found: /api/v3/stages/authenticator/duo/37c15022-1ee2-49e0-a055-ef165648e0c6/enrollment_status/", "level": "warning", "logger": "django.request", "timestamp": 1662906785.468911}
{"auth_via": "session", "event": "/api/v3/stages/authenticator/duo/37c15022-1ee2-49e0-a055-ef165648e0c6/enrollment_status/", "host": "REDACTED", "level": "info", "logger": "authentik.asgi", "method": "POST", "pid": 21, "remote": "192.168.36.17", "request_id": "749c18439fbb48388a3f40e6578747e2", "runtime": 18, "scheme": "https", "status": 404, "timestamp": "2022-09-11T14:33:08.397027", "user": "luukrijnbende", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"}
{"event": "Not Found: /api/v3/stages/authenticator/duo/37c15022-1ee2-49e0-a055-ef165648e0c6/enrollment_status/", "level": "warning", "logger": "django.request", "timestamp": 1662906788.3974037}
{"auth_via": "session", "event": "/api/v3/stages/authenticator/duo/37c15022-1ee2-49e0-a055-ef165648e0c6/enrollment_status/", "host": "REDACTED", "level": "info", "logger": "authentik.asgi", "method": "POST", "pid": 22, "remote": "192.168.36.17", "request_id": "6e4f2eedb99d4dd68c9ef169ea765937", "runtime": 20, "scheme": "https", "status": 404, "timestamp": "2022-09-11T14:33:11.399975", "user": "luukrijnbende", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"}
{"event": "Not Found: /api/v3/stages/authenticator/duo/37c15022-1ee2-49e0-a055-ef165648e0c6/enrollment_status/", "level": "warning", "logger": "django.request", "timestamp": 1662906791.400293}
{"auth_via": "unauthenticated", "event": "/-/health/ready/", "host": "10.42.1.70:9000", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 22, "remote": "10.42.1.1", "request_id": "79f9184a9630481d8f9840dbcabc8308", "runtime": 9, "scheme": "http", "status": 204, "timestamp": "2022-09-11T14:33:11.889956", "user": "", "user_agent": "kube-probe/1.20"}
{"auth_via": "session", "event": "/api/v3/stages/authenticator/duo/37c15022-1ee2-49e0-a055-ef165648e0c6/enrollment_status/", "host": "REDACTED", "level": "info", "logger": "authentik.asgi", "method": "POST", "pid": 22, "remote": "192.168.36.17", "request_id": "57b50c81ce8c418bb65d466d922d78c7", "runtime": 18, "scheme": "https", "status": 404, "timestamp": "2022-09-11T14:33:14.398208", "user": "luukrijnbende", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"}
{"event": "Not Found: /api/v3/stages/authenticator/duo/37c15022-1ee2-49e0-a055-ef165648e0c6/enrollment_status/", "level": "warning", "logger": "django.request", "timestamp": 1662906794.3985548}
{"auth_via": "session", "event": "/api/v3/stages/authenticator/duo/37c15022-1ee2-49e0-a055-ef165648e0c6/enrollment_status/", "host": "REDACTED", "level": "info", "logger": "authentik.asgi", "method": "POST", "pid": 21, "remote": "192.168.36.17", "request_id": "99f757d8cda54a3da0150f1daf7a99ff", "runtime": 20, "scheme": "https", "status": 404, "timestamp": "2022-09-11T14:33:16.630543", "user": "luukrijnbende", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"}
{"event": "Not Found: /api/v3/stages/authenticator/duo/37c15022-1ee2-49e0-a055-ef165648e0c6/enrollment_status/", "level": "warning", "logger": "django.request", "timestamp": 1662906796.630886}
{"auth_via": "session", "event": "/api/v3/stages/authenticator/duo/37c15022-1ee2-49e0-a055-ef165648e0c6/enrollment_status/", "host": "REDACTED", "level": "info", "logger": "authentik.asgi", "method": "POST", "pid": 21, "remote": "192.168.36.17", "request_id": "98ba00f3da5c488b88301f1a24f8fe56", "runtime": 18, "scheme": "https", "status": 404, "timestamp": "2022-09-11T14:33:17.409435", "user": "luukrijnbende", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"}
{"event": "Not Found: /api/v3/stages/authenticator/duo/37c15022-1ee2-49e0-a055-ef165648e0c6/enrollment_status/", "level": "warning", "logger": "django.request", "timestamp": 1662906797.4097602}
{"auth_via": "session", "event": "/api/v3/stages/authenticator/duo/37c15022-1ee2-49e0-a055-ef165648e0c6/enrollment_status/", "host": "REDACTED", "level": "info", "logger": "authentik.asgi", "method": "POST", "pid": 22, "remote": "192.168.36.17", "request_id": "148d6ea3d57845489c10c80283b57374", "runtime": 16, "scheme": "https", "status": 404, "timestamp": "2022-09-11T14:33:21.113171", "user": "luukrijnbende", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"}
{"event": "Not Found: /api/v3/stages/authenticator/duo/37c15022-1ee2-49e0-a055-ef165648e0c6/enrollment_status/", "level": "warning", "logger": "django.request", "timestamp": 1662906801.1197739}
{"auth_via": "unauthenticated", "event": "/-/health/ready/", "host": "10.42.1.70:9000", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 22, "remote": "10.42.1.1", "request_id": "d126e804a36f469da7dffd9017d658eb", "runtime": 10, "scheme": "http", "status": 204, "timestamp": "2022-09-11T14:33:21.890977", "user": "", "user_agent": "kube-probe/1.20"}
{"auth_via": "session", "event": "/api/v3/events/events/?ordering=-created&page=1&page_size=20&search=", "host": "REDACTED", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 22, "remote": "192.168.36.17", "request_id": "02eb2628f81d4d058e83a3b3e668e36f", "runtime": 19, "scheme": "https", "status": 200, "timestamp": "2022-09-11T14:33:22.285129", "user": "akadmin", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"}
{"auth_via": "session", "event": "/api/v3/stages/authenticator/duo/37c15022-1ee2-49e0-a055-ef165648e0c6/enrollment_status/", "host": "REDACTED", "level": "info", "logger": "authentik.asgi", "method": "POST", "pid": 22, "remote": "192.168.36.17", "request_id": "aabece42b02c41f6bedb37a999607e5a", "runtime": 21, "scheme": "https", "status": 404, "timestamp": "2022-09-11T14:33:24.113233", "user": "luukrijnbende", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"}
{"event": "Not Found: /api/v3/stages/authenticator/duo/37c15022-1ee2-49e0-a055-ef165648e0c6/enrollment_status/", "level": "warning", "logger": "django.request", "timestamp": 1662906804.113649}
{"auth_via": "session", "event": "/api/v3/stages/authenticator/duo/37c15022-1ee2-49e0-a055-ef165648e0c6/enrollment_status/", "host": "REDACTED", "level": "info", "logger": "authentik.asgi", "method": "POST", "pid": 22, "remote": "192.168.36.17", "request_id": "48947576c5204dc7b811780d3a49aa93", "runtime": 20, "scheme": "https", "status": 404, "timestamp": "2022-09-11T14:33:30.114316", "user": "luukrijnbende", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"}
{"event": "Not Found: /api/v3/stages/authenticator/duo/37c15022-1ee2-49e0-a055-ef165648e0c6/enrollment_status/", "level": "warning", "logger": "django.request", "timestamp": 1662906810.1146352}
{"auth_via": "unauthenticated", "event": "/-/health/ready/", "host": "10.42.1.70:9000", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 22, "remote": "10.42.1.1", "request_id": "da6e27e6620f426e8b9b56d4b449c05b", "runtime": 9, "scheme": "http", "status": 204, "timestamp": "2022-09-11T14:33:31.890398", "user": "", "user_agent": "kube-probe/1.20"}
{"auth_via": "session", "event": "/api/v3/stages/authenticator/duo/37c15022-1ee2-49e0-a055-ef165648e0c6/enrollment_status/", "host": "REDACTED", "level": "info", "logger": "authentik.asgi", "method": "POST", "pid": 22, "remote": "192.168.36.17", "request_id": "87fc34b9f13c40d48f0de72b1259eacf", "runtime": 24, "scheme": "https", "status": 404, "timestamp": "2022-09-11T14:33:33.116345", "user": "luukrijnbende", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"}
{"event": "Not Found: /api/v3/stages/authenticator/duo/37c15022-1ee2-49e0-a055-ef165648e0c6/enrollment_status/", "level": "warning", "logger": "django.request", "timestamp": 1662906813.1167731}
{"auth_via": "session", "event": "/api/v3/stages/authenticator/duo/37c15022-1ee2-49e0-a055-ef165648e0c6/enrollment_status/", "host": "REDACTED", "level": "info", "logger": "authentik.asgi", "method": "POST", "pid": 21, "remote": "192.168.36.17", "request_id": "2acf96ccd9e542aaa1733fa0d951607c", "runtime": 19, "scheme": "https", "status": 404, "timestamp": "2022-09-11T14:33:36.114889", "user": "luukrijnbende", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"}
{"event": "Not Found: /api/v3/stages/authenticator/duo/37c15022-1ee2-49e0-a055-ef165648e0c6/enrollment_status/", "level": "warning", "logger": "django.request", "timestamp": 1662906816.1153579}
{"auth_via": "session", "event": "/api/v3/stages/authenticator/duo/37c15022-1ee2-49e0-a055-ef165648e0c6/enrollment_status/", "host": "REDACTED", "level": "info", "logger": "authentik.asgi", "method": "POST", "pid": 21, "remote": "192.168.36.17", "request_id": "7680e880bdaf4413a416d082903fb557", "runtime": 21, "scheme": "https", "status": 404, "timestamp": "2022-09-11T14:33:39.111294", "user": "luukrijnbende", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"}
{"event": "Not Found: /api/v3/stages/authenticator/duo/37c15022-1ee2-49e0-a055-ef165648e0c6/enrollment_status/", "level": "warning", "logger": "django.request", "timestamp": 1662906819.111754}
{"auth_via": "unauthenticated", "event": "/-/health/ready/", "host": "10.42.1.70:9000", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 22, "remote": "10.42.1.1", "request_id": "129f0790870f4bb39be2519958bfaf0d", "runtime": 9, "scheme": "http", "status": 204, "timestamp": "2022-09-11T14:33:41.891064", "user": "", "user_agent": "kube-probe/1.20"}
{"auth_via": "session", "event": "/api/v3/stages/authenticator/duo/37c15022-1ee2-49e0-a055-ef165648e0c6/enrollment_status/", "host": "REDACTED", "level": "info", "logger": "authentik.asgi", "method": "POST", "pid": 22, "remote": "192.168.36.17", "request_id": "2842d7b007924ad3b719502dc5882e03", "runtime": 20, "scheme": "https", "status": 404, "timestamp": "2022-09-11T14:33:42.114480", "user": "luukrijnbende", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"}
{"event": "Not Found: /api/v3/stages/authenticator/duo/37c15022-1ee2-49e0-a055-ef165648e0c6/enrollment_status/", "level": "warning", "logger": "django.request", "timestamp": 1662906822.114857}
{"auth_via": "session", "event": "/api/v3/stages/authenticator/duo/37c15022-1ee2-49e0-a055-ef165648e0c6/enrollment_status/", "host": "REDACTED", "level": "info", "logger": "authentik.asgi", "method": "POST", "pid": 21, "remote": "192.168.36.17", "request_id": "f6258f97c55a468895502d0b3d001038", "runtime": 20, "scheme": "https", "status": 404, "timestamp": "2022-09-11T14:33:45.121317", "user": "luukrijnbende", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"}
{"event": "Not Found: /api/v3/stages/authenticator/duo/37c15022-1ee2-49e0-a055-ef165648e0c6/enrollment_status/", "level": "warning", "logger": "django.request", "timestamp": 1662906825.1217933}
{"auth_via": "session", "event": "/api/v3/stages/authenticator/duo/37c15022-1ee2-49e0-a055-ef165648e0c6/enrollment_status/", "host": "REDACTED", "level": "info", "logger": "authentik.asgi", "method": "POST", "pid": 21, "remote": "192.168.36.17", "request_id": "25b816093145496591fc13c9c328c6b4", "runtime": 22, "scheme": "https", "status": 404, "timestamp": "2022-09-11T14:33:48.124902", "user": "luukrijnbende", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"}
{"event": "Not Found: /api/v3/stages/authenticator/duo/37c15022-1ee2-49e0-a055-ef165648e0c6/enrollment_status/", "level": "warning", "logger": "django.request", "timestamp": 1662906828.1252992}
{"auth_via": "session", "event": "/api/v3/stages/authenticator/duo/37c15022-1ee2-49e0-a055-ef165648e0c6/enrollment_status/", "host": "REDACTED", "level": "info", "logger": "authentik.asgi", "method": "POST", "pid": 22, "remote": "192.168.36.17", "request_id": "2db8ec2a7fd54514b5910f180c1189bc", "runtime": 21, "scheme": "https", "status": 404, "timestamp": "2022-09-11T14:33:51.115519", "user": "luukrijnbende", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"}
{"event": "Not Found: /api/v3/stages/authenticator/duo/37c15022-1ee2-49e0-a055-ef165648e0c6/enrollment_status/", "level": "warning", "logger": "django.request", "timestamp": 1662906831.1158962}
{"auth_via": "unauthenticated", "event": "/-/health/ready/", "host": "10.42.1.70:9000", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 22, "remote": "10.42.1.1", "request_id": "d11590faba6f4b87b542579ab788863a", "runtime": 7, "scheme": "http", "status": 204, "timestamp": "2022-09-11T14:33:51.887774", "user": "", "user_agent": "kube-probe/1.20"}
{"auth_via": "session", "event": "/api/v3/stages/authenticator/duo/37c15022-1ee2-49e0-a055-ef165648e0c6/enrollment_status/", "host": "REDACTED", "level": "info", "logger": "authentik.asgi", "method": "POST", "pid": 21, "remote": "192.168.36.17", "request_id": "c3156154a9de4dd791cdd460677aa02c", "runtime": 20, "scheme": "https", "status": 404, "timestamp": "2022-09-11T14:33:54.124849", "user": "luukrijnbende", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"}
{"event": "Not Found: /api/v3/stages/authenticator/duo/37c15022-1ee2-49e0-a055-ef165648e0c6/enrollment_status/", "level": "warning", "logger": "django.request", "timestamp": 1662906834.1252718}
{"auth_via": "session", "event": "/api/v3/stages/authenticator/duo/37c15022-1ee2-49e0-a055-ef165648e0c6/enrollment_status/", "host": "REDACTED", "level": "info", "logger": "authentik.asgi", "method": "POST", "pid": 22, "remote": "192.168.36.17", "request_id": "3259e31479e244c9b3baa6a1ab9d133a", "runtime": 19, "scheme": "https", "status": 404, "timestamp": "2022-09-11T14:33:57.113774", "user": "luukrijnbende", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"}
{"event": "Not Found: /api/v3/stages/authenticator/duo/37c15022-1ee2-49e0-a055-ef165648e0c6/enrollment_status/", "level": "warning", "logger": "django.request", "timestamp": 1662906837.1177688}
{"auth_via": "unauthenticated", "event": "/-/health/live/", "host": "localhost:8000", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 22, "remote": "127.0.0.1", "request_id": "a655873c82bf49088ba8861d0596290a", "runtime": 8, "scheme": "http", "status": 204, "timestamp": "2022-09-11T14:33:59.316145", "user": "", "user_agent": "goauthentik.io/proxy/healthcheck"}
{"auth_via": "session", "event": "/api/v3/stages/authenticator/duo/37c15022-1ee2-49e0-a055-ef165648e0c6/enrollment_status/", "host": "REDACTED", "level": "info", "logger": "authentik.asgi", "method": "POST", "pid": 22, "remote": "192.168.36.17", "request_id": "bf113a2a6dde4f36a1547704a479bf1c", "runtime": 18, "scheme": "https", "status": 404, "timestamp": "2022-09-11T14:34:00.104532", "user": "luukrijnbende", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"}
{"event": "Not Found: /api/v3/stages/authenticator/duo/37c15022-1ee2-49e0-a055-ef165648e0c6/enrollment_status/", "level": "warning", "logger": "django.request", "timestamp": 1662906840.1108816}
{"auth_via": "unauthenticated", "event": "/-/health/ready/", "host": "10.42.1.70:9000", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 22, "remote": "10.42.1.1", "request_id": "599d60c13837413c986fcf4169f082ff", "runtime": 9, "scheme": "http", "status": 204, "timestamp": "2022-09-11T14:34:01.890328", "user": "", "user_agent": "kube-probe/1.20"}
{"auth_via": "session", "event": "/api/v3/stages/authenticator/duo/37c15022-1ee2-49e0-a055-ef165648e0c6/enrollment_status/", "host": "REDACTED", "level": "info", "logger": "authentik.asgi", "method": "POST", "pid": 22, "remote": "192.168.36.17", "request_id": "e783240f9b1c471bb272eb4ffe5c9a30", "runtime": 19, "scheme": "https", "status": 404, "timestamp": "2022-09-11T14:34:03.118376", "user": "luukrijnbende", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"}
{"event": "Not Found: /api/v3/stages/authenticator/duo/37c15022-1ee2-49e0-a055-ef165648e0c6/enrollment_status/", "level": "warning", "logger": "django.request", "timestamp": 1662906843.1217422}
{"auth_via": "session", "event": "/api/v3/stages/authenticator/duo/37c15022-1ee2-49e0-a055-ef165648e0c6/enrollment_status/", "host": "REDACTED", "level": "info", "logger": "authentik.asgi", "method": "POST", "pid": 21, "remote": "192.168.36.17", "request_id": "9b225e1189aa4c15a3cde23263b99989", "runtime": 20, "scheme": "https", "status": 404, "timestamp": "2022-09-11T14:34:06.115612", "user": "luukrijnbende", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"}
{"event": "Not Found: /api/v3/stages/authenticator/duo/37c15022-1ee2-49e0-a055-ef165648e0c6/enrollment_status/", "level": "warning", "logger": "django.request", "timestamp": 1662906846.1219172}
{"auth_via": "session", "event": "/api/v3/stages/authenticator/duo/37c15022-1ee2-49e0-a055-ef165648e0c6/enrollment_status/", "host": "REDACTED", "level": "info", "logger": "authentik.asgi", "method": "POST", "pid": 21, "remote": "192.168.36.17", "request_id": "7a828b87c7284b69bd2bd67fb4dd315a", "runtime": 19, "scheme": "https", "status": 404, "timestamp": "2022-09-11T14:34:09.106312", "user": "luukrijnbende", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"}
{"event": "Not Found: /api/v3/stages/authenticator/duo/37c15022-1ee2-49e0-a055-ef165648e0c6/enrollment_status/", "level": "warning", "logger": "django.request", "timestamp": 1662906849.106656}
{"auth_via": "unauthenticated", "event": "/-/health/ready/", "host": "10.42.1.70:9000", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 22, "remote": "10.42.1.1", "request_id": "cf2299215b11498d97c1ce0e8b384f16", "runtime": 10, "scheme": "http", "status": 204, "timestamp": "2022-09-11T14:34:11.891589", "user": "", "user_agent": "kube-probe/1.20"}
{"auth_via": "session", "event": "/api/v3/stages/authenticator/duo/37c15022-1ee2-49e0-a055-ef165648e0c6/enrollment_status/", "host": "REDACTED", "level": "info", "logger": "authentik.asgi", "method": "POST", "pid": 22, "remote": "192.168.36.17", "request_id": "7b88e7919af445edb3a5f236db2af7a1", "runtime": 20, "scheme": "https", "status": 404, "timestamp": "2022-09-11T14:34:12.121258", "user": "luukrijnbende", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"}
{"event": "Not Found: /api/v3/stages/authenticator/duo/37c15022-1ee2-49e0-a055-ef165648e0c6/enrollment_status/", "level": "warning", "logger": "django.request", "timestamp": 1662906852.1216328}
```

**Comment by BeryJu** [comment]
Hmmm, no error messages which is very interesting, is the user you're trying to enroll a non-superuser by any chance? I'm wondering if there's a bug with that API endpoint that requires a permission that normal users don't have

**Comment by BeryJu** [comment]
Yep, indeed that was the case, the API endpoint itself didn't require extra permissions but I forgot that `self.get_object()` checks permissions, which is not what we want in this case

**Comment by luukrijnbende** [comment]
It works now, thanks! 😄

**Comment by DaveB91** [comment]
Cloudflare
