### ISSUE TITLE
guacamole redirect loop due to invalid x5c JWKS value

### ISSUE THREAD

**Issue by tmolbergen** [goauthentik/authentik#4082]
**Describe the bug**
Guacamole authentication with authentik goes into a redirect loop

**To Reproduce**
1. Browse to your guacamole 
2. -> "redirects to authentik" 
3. Sign in
4. Infinite redirect loop

**Expected behavior**
Expected behaviour is to access guacamole

**Screenshots**
A redirect loop probably dosent need a screenshot

**Logs**
Not sure if I want to share logs as they contain a lot of details which dosent necessarily belong on GitHub.
Can send logs on the side if required. 

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.11.1
 - Deployment: docker-compose

**Additional context**
Only change was an upgrade from 2022.6.x to 2022.11 version. Tried checked various logs but nothing seems to stick out at the moment. In the Authentik logs I can see repeated entries with "Model created" -> "Application authorised"

Same issue has been reported on versions:
2022.8.2

**Comment by tmolberg** [comment]
For what its worth, here is the error message from guacamole. I've removed the JWT token on purpose; 
Could it be that the certificates are malformed when presented? 


[2022-11-24 11:46:25] [info] 11:46:25.271 [http-nio-8080-exec-3] INFO  o.a.g.a.o.t.TokenValidationService - Rejected invalid OpenID token: JWT processing failed. Additional details: [[17] Unable to process JOSE object (cause: org.jose4j.lang.UnresolvableKeyException: Unable to find a suitable verification key for JWS w/ header {"alg":"RS256","kid":"6b291e79896e45b5a6c0488d464d113f","typ":"JWT"} from JWKs [] obtained from https://authentik.tmolberg.net/application/o/guac/jwks/): JsonWebSignature{"alg":"RS256","kid":"6b291e79896e45b5a6c0488d464d113f","typ":"JWT"}

**Comment by tomlawesome** [comment]
Also running into this issue and have been unable to resolve it. I believe this is a certificate issue, but have tried the following: 

- Manually add self-signed cert + key pair to Authentik, add the cert from this pair into Guacamole's java cacerts store. This previously worked, but no longer does. 
- The same procedure above, but using a valid LetsEncrypt certificate pair added to Authentik. Definitely valid, I use it elsewhere without issue. 
- The same procedure above but using Cloudflare origin certs added to Authentik/Guac, which also previously worked but no longer does.

**Comment by MiGoller** [comment]
Same issue here.

**Comment by Maggsi** [comment]
Had the same issue after updating to 2022.11.3
Generating a new self signed certificate worked for me - even though the default self signed cert has not expired yet...

**Comment by tmolberg** [comment]
Awesome, that workaround did the treat for me.

**Comment by BeryJu** [comment]
The only certificate-related change that I could imagine impacting this is the change from 2048 bit to 4096 bit private keys, however that's been changed since 2021.12.4. The other important thing is that guacamole needs to be restarted whenever the signing key in authentik is changed, as guacamole only gets that info from authentik on startup

The thing that looks a bit odd in the logs is `from JWKs [] obtained from`, indicating that no JWKs have been received, even when there are keys selected

Adding the authentik certificates or using lets encrypt certificates doesn't make a difference for this as this is completely unrelated, and has nothing per-se to do with traditional certificate validation

**Comment by tmolberg** [comment]
I assumed as much as adding the authentik & letsencrypt certificate shouldnt make a difference - Therefore I didnt do that. 

Though I do find it interesting that the change from 2048 bit to 4096 bit private keys could cause this. Could it be a mismatch between the first generated certifcate and the expectation from the certificate? 2048 vs 4096? 

Recreating the self signed certificate and assigning that to the application sounds like a plausible fix if im understanding the problem correctly.

**Comment by BeryJu** [comment]
My reason for suspecting the 2048 -> 4096 bit change is that some applications classify 2048 bit keys as insecure and ignore them, however I haven't checked if guac does this, as I haven't been able to reproduce this issue

**Comment by Maggsi** [comment]
I did not restart anything in my guacamole compose project after generating the new self signed cert and assigning that to the provider.

I started authentik after the update a few days ago, restarted the guac compose today a few times while troubleshooting this, tried guacamole and got redirect looped, generated a new self signed cert, assigned that to the provider and opened guacamole in a new tab - now working without a loop

After seeing it work i restarted all my guacamole services and they still work after a reboot.

Switching back to the original self signed cert starts the loop again, no reboot required.

My original self signed cert has an expiry date of 17.03.2023 - maybe that helps us figure out what version it was generated in? I'm sure it was the latest version at the time

**Comment by BeryJu** [comment]
the default expiry is 1 year so it will have been generated on 17.03.2022, so probably one of the early 2022.x versions (which all already have the 4096 bit key generation)

If you don't use the old certificate for anything else, could you post it for testing reasons? I'll try with 2022.1.x and upgrade to the latest to see if that makes a difference

**Comment by BeryJu** [comment]
Ok after some more testing:

- Guacamole seems to check the JWKS endpoint on each authentication, so it doesn't have to be restarted 
- I can reproduce the loop when initially configuring guac with 2022.1.1 and then upgrading to latest

**Comment by tomlawesome** [comment]
For myself -- perhaps I'm doing something wrong -- generating a new certificate/key pair and assigning it to the Guac provider does not break the redirect loop. 

I have, in order:

1. Updated all authentik & guacamole/guacd containers just now
2. Generated a new cert/key pair in guac
3. Applied the new cert as the signing key in the Guacamole provider in Authentik
4. Restarted Guacamole and Guacd
5. Restarted Authentik (all containers) *and* then restarted Guacamole/Guacd. 

I continue to get the redirect loop. @BeryJu I would be happy to send logs or anything that may be of assistance. I'm unsure which bits are sensitive so don't want to post publicly by preference.

**Comment by BeryJu** [comment]
guacamole seems to not like the x5c value that authentik's JWKS endpoint returns, and completely disregards the JWK instead of saying why it's invalid

And yeah this only happens with newer generated certificates

there is one other thing that changed with the default generated certificate, the newer ones get a Subject Alternate Name of `goauthentik.io` while the old ones don't get that

**Comment by timnis** [comment]
Looks like same problem also with Keycloak 22.0.2
`
16:28:13.882 [http-nio-8080-exec-10] INFO  o.a.g.a.o.t.TokenValidationService - Rejected invalid OpenID token: JWT processing failed. Additional details: [[17] Unable to process JOSE object (cause: org.jose4j.lang.UnresolvableKeyException: Unable to find a suitable verification key for JWS w/ header {"alg":"RS256","typ" : "JWT","kid" : "LaAKcXQe35CMuemrPU3S3IrkTYh6DqKpF3fmx6kJJdE"} due to an unexpected exception (java.io.IOException: Non 200 status code (403 Forbidden) returned from https://id.xxxxxx.com/realms/master/protocol/openid-connect/certs) while obtaining or using keys from JWKS endpoint at https://id.xxxxxx.com/realms/,aster/protocol/openid-connect/certs): JsonWebSignature{"alg":"RS256","typ" : "JWT","kid" : "LaAKcXQe35CMuem
`

**Comment by mattisz** [comment]
@timnis it looks like you have a typo here:
`while obtaining or using keys from JWKS endpoint at https://id.xxxxxx.com/realms/**,aster**/protocol/openid-connect/certs`
Not sure if that typo is directly from your configuration of authentik/guacamole or if that happened when you were redacting your domain but definitely worth looking in to.

**Comment by BeryJu** [comment]
this seems to be some sort of edge case in the JWKS view in authentik, as I've had some occasionally flaky tests for that view as well. However I haven't been able fix it yet, so the PR above adds a workaround in the next version

**Comment by BeryJu** [comment]
So the flaky tests were actually a result of ECDSA JWKs keys when the x and y coordinates aren't the same length, which doesn't seem to make a difference for guacamole.

**Comment by BeryJu** [comment]
So finally, the actual issue itself was caused by a bug in the certificate generator in authentik, when not specifying and Subject Alternate names. As a workaround, generate a certificate and specify anything in the SAN field, and in the next authentik version this will be fixed even with a blank input

**Comment by emqMalte** [comment]
I'm sorry, but is this fix available in the current version?
Today I updated to 2023.1.2 and attempted to set up openid via the instructions from https://goauthentik.io/integrations/services/apache-guacamole/ with the current Guacamole versions but ran into the same error message that was mentioned here before.

I also attempted to create new certificates in authentik, with and without the SAN filled out, tried each as the Signing Key in the Provider I used for Guacamole and restarted all the things. 

Yet the error continued to show up

> 22:03:59.418 [http-nio-8080-exec-2] INFO  o.a.g.a.o.t.TokenValidationService - Rejected invalid OpenID token: JWT processing failed. Additional details: [[17] Unable to process JOSE object (cause: org.jose4j.lang.UnresolvableKeyException: Unable to find a suitable verification key for JWS w/ header {"alg":"RS256","kid":"xxx","typ":"JWT"} due to an unexpected exception (java.io.IOException: Non 200 status code (403 Forbidden) returned from https://example.com/application/o/guacamole/jwks/?exclude_x5) while obtaining or using keys from JWKS endpoint at https:///example.com/application/o/guacamole/jwks/?exclude_x5): JsonWebSignature{"alg":"RS256","kid":"xxx","typ":"JWT"}->ey...

**Comment by BeryJu** [comment]
403 is a different issue and most likely caused by cloudflare blocking the request

**Comment by kotoxie** [comment]
still an issue in 2023.10.3 - @BeryJu any plans to resolve it?

**Comment by Fma965** [comment]
> still an issue in 2023.10.3 - @BeryJu any plans to resolve it?

Did you check cloudflare or other web firewall like mentioned above

**Comment by bamhm182** [comment]
I believe I am also running into issues around this. I have been trying to ensure I'm not missing something dumb, as it seems other have been able to get guacamole working, and I may be having unrelated DNS issues. Reviewing the PR that was supposed to fix this, though, it looks like it is expected that if we throw in `exclude_x5` as a GET parameter, it should remove the `x5*` keys from the jwks json. At the same time, it looks like that may have been removed prior to the merge. I can confirm that adding `exclude_x5` does nothing for me, and that the code doesn't appear to be in place in the current jwks view.

Can someone confirm that guacamole is working for them even when the `x5*` keys remain in the jwks URL that Guacamole is given?

I am currently trying with 2023.10.3, but tried 2023.8.4 in case it was a recent regression, before digging into main and coming to my current conclusion that `exclude_x5` may have never existed on main.

**Comment by kotoxie** [comment]
> > still an issue in 2023.10.3 - @BeryJu any plans to resolve it?
> 
> Did you check cloudflare or other web firewall like mentioned above

After plating around I finally was able to get the 403 error, no idea what led to this.
I whitelisted it in Cloudflare (wasn't running it behind proxy for testing), it somehow now works

**Comment by bamhm182** [comment]
After days of kicking my own butt, I finally got it! My issues had nothing to do with Authentik or Guacamole and everything to do with a lot of the jank I have in place to make podman work the way I want it to. Here's the relevant guacamole container environment variables that are working for me at this moment:

```
OPENID_AUTHORIZATION_ENDPOINT=https://authentik.example.com/application/o/authorize/
OPENID_CLIENT_ID=xxx
OPENID_ISSUER=https://authentik.example.com/application/o/guacamole/
OPENID_JWKS_ENDPOINT=https://authentik.example.com/application/o/guacamole/jwks/
OPENID_REDIRECT_URI=https://guacamole.example.com/
```
I am using `guacamole/guacamole:latest` (1.5.3) and `ghcr.io/goauthentik/server:2023.10.3`.

**Comment by Jakobabs** [comment]
For anyone else having this issue, I tried all of the above methods and none of them worked. I am using Unraid's ApacheGuacamole container so finding the correct logs for guac was under "log/tomcat/catalina.out" which i found the following error (I removed unnecessary details): 

Issuer (iss) claim value (https://authentik.example.com:443/application/o/guacamole/) doesn't match expected value of https://authentik.example.com/application/o/guacamole/]

In my guacamole config I just had to add the port to my OPENID_ISSUER variable and it fixed the loop.
Hope this helps!

**Comment by julianq** [comment]
I wanted to add another solution if anybody comes across this (using authentik as oidc provider).

I was having a redirect loop and `/var/log/tomcat9/catalina.out` was showing (also removing unnecessary details):

`Issuer (iss) claim value ([http://authentik.example.com/application/o/guacamole/](https://authentik.example.com/application/o/guacamole/)) doesn't match expected value of [https://authentik.example.com/application/o/guacamole/]](https://authentik.example.com/application/o/guacamole/)`

This was ultimately solved by changing the scheme from `https` to `http` in `OPENID_ISSUER`

```
OPENID_AUTHORIZATION_ENDPOINT=https://authentik.example.com/application/o/authorize/
OPENID_CLIENT_ID=xxx
OPENID_ISSUER=http://authentik.example.com/application/o/guacamole/
OPENID_JWKS_ENDPOINT=https://authentik.example.com/application/o/guacamole/jwks/
OPENID_REDIRECT_URI=https://guacamole.example.com/
```

**Comment by LukePWilkins** [comment]
Thank you @Fma965, the Browser Integrity Check was causing a failure with me as well. Your rule worked for me too.
