### ISSUE TITLE
Email failing send during stage, not when using ak test_email command

### ISSUE THREAD

**Issue by adamzvolanek** [goauthentik/authentik#4293]
**Describe the bug**
I am finding errors when sending emails using SMTP, however when using the ak test_email from [the official docs](https://goauthentik.io/docs/troubleshooting/emails) the email gets sent.

**To Reproduce**
1. Create an email stage with global settings.
![image](https://user-images.githubusercontent.com/80661527/209764601-61485749-b1f1-4653-a83e-4445aeaf12bb.png)
2. Open an incognito window and try to recover password using account name or email used.+
![image](https://user-images.githubusercontent.com/80661527/209764676-2b74c2b1-ca98-4b12-a642-8f7df38c040f.png)
4. Press continue to allow email to send. 
5. See error 
![image](https://user-images.githubusercontent.com/80661527/209764786-b18dea50-17da-43f1-9172-eef8bb31f104.png)

This does not occur when issuing the command, `ak test_email <my email address> -s recovery-stage
`

**Expected behavior**
I expected given the global settings checked that there would not be a block of the ports, however this is not the case. I did not restrict ports in any, at least not explicitly.

**Screenshots**
Docker setup including ports:
![image](https://user-images.githubusercontent.com/80661527/209765141-6a03961c-1dab-4e03-94aa-14104c3e3091.png)

**Logs**
```
Context
{
    "message": "Task send_mail encountered an error: Traceback (most recent call last):\n  File \"/usr/local/lib/python3.11/site-packages/celery/app/trace.py\", line 451, in trace_task\n    R = retval = fun(*args, **kwargs)\n                 ^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sentry_sdk/integrations/celery.py\", line 207, in _inner\n    reraise(*exc_info)\n  File \"/usr/local/lib/python3.11/site-packages/sentry_sdk/_compat.py\", line 57, in reraise\n    raise value\n  File \"/usr/local/lib/python3.11/site-packages/sentry_sdk/integrations/celery.py\", line 202, in _inner\n    return f(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/celery/app/trace.py\", line 734, in __protected_call__\n    return self.run(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/celery/app/autoretry.py\", line 54, in run\n    ret = task.retry(exc=exc, **retry_kwargs)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/celery/app/task.py\", line 717, in retry\n    raise_with_context(exc)\n  File \"/usr/local/lib/python3.11/site-packages/celery/app/autoretry.py\", line 34, in run\n    return task._orig_run(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/authentik/stages/email/tasks.py\", line 103, in send_mail\n    raise exc\n  File \"/authentik/stages/email/tasks.py\", line 73, in send_mail\n    backend.open()\n  File \"/usr/local/lib/python3.11/site-packages/django/core/mail/backends/smtp.py\", line 80, in open\n    self.connection = self.connection_class(\n                      ^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/smtplib.py\", line 255, in __init__\n    (code, msg) = self.connect(host, port)\n                  ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/smtplib.py\", line 341, in connect\n    self.sock = self._get_socket(host, port, self.timeout)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/smtplib.py\", line 312, in _get_socket\n    return socket.create_connection((host, port), timeout,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/socket.py\", line 850, in create_connection\n    raise exceptions[0]\n  File \"/usr/local/lib/python3.11/socket.py\", line 835, in create_connection\n    sock.connect(sa)\nbuiltins.OSError: [Errno 99] Cannot assign requested address"
}
User
{}
```

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.11.4
 - Deployment: docker (Unraid)

**Comment by adamzvolanek** [comment]
This issue remains present for version 2022.12.2

**Comment by adamzvolanek** [comment]
Fixed the gmail issue by putting the same variables as pictured above with the addition of email__timeout. 
```
      # Authentik Email Settings
      - AUTHENTIK_EMAIL__HOST: ${AUTHENTIK_EMAIL__HOST}
      - AUTHENTIL_EMAIL__PORT: ${AUTHENTIK_EMAIL__PORT}
      - AUTHENTIK_EMAIL__USERNAME: ${AUTHENTIK_EMAIL__USERNAME}
      - AUTHENTIK_EMAIL__PASSWORD: ${AUTHENTIK_EMAIL_PASSWORD}
      - AUTHENTIK_EMAIL__USE_TLS: ${AUTHENTIK_EMAIL__USE_TLS}
      - AUTHENTIK_EMAIL__USE_SSL: ${AUTHENTIK_EMAIL__USE_SSL}
      - AUTHENTIK_EMAIL__TIMEOUT: ${AUTHENTIK_EMAIL__TIMEOUT}
      - AUTHENTIK_EMAIL__FROM: ${AUTHENTIK_EMAIL__FROM}
      - AUTHENTIK_EMAIL__TIMEOUT: 10
```

The email__from variable does not seem to be working correctly and defaulting to my email__username, however I will tinker to see if it is a configuration issue on my end.

**Comment by boolbyte** [comment]
Did you figure this out? I seem to be having the same issue...

**Comment by adamzvolanek** [comment]
> Did you figure this out? I seem to be having the same issue...

Yes see my solution above. Let me know if it doesn't work for you, I can try to steer you in the right direction.

**Comment by boolbyte** [comment]
I set the smtp directly in the email stage, this fixed it for me.
Not sure what's going on with the Environment variables.

**Comment by davidjmorin** [comment]
I am also having this issue.  the above 'fix" did not work for me.

**Comment by boolbyte** [comment]
These are my settings during the email stage for an outlook account.
If you are using an outlook or hotmail account, you will need to setup an app password in Microsoft account settings.

![image](https://user-images.githubusercontent.com/13240106/213036073-e6013543-65f8-4acb-bd44-d1c21e044377.png)

**Comment by davidjmorin** [comment]
> Fixed the gmail issue by putting the same variables as pictured above with the addition of email__timeout.
> 
> ```
>       # Authentik Email Settings
>       - AUTHENTIK_EMAIL__HOST: ${AUTHENTIK_EMAIL__HOST}
>       - AUTHENTIL_EMAIL__PORT: ${AUTHENTIK_EMAIL__PORT}
>       - AUTHENTIK_EMAIL__USERNAME: ${AUTHENTIK_EMAIL__USERNAME}
>       - AUTHENTIK_EMAIL__PASSWORD: ${AUTHENTIK_EMAIL_PASSWORD}
>       - AUTHENTIK_EMAIL__USE_TLS: ${AUTHENTIK_EMAIL__USE_TLS}
>       - AUTHENTIK_EMAIL__USE_SSL: ${AUTHENTIK_EMAIL__USE_SSL}
>       - AUTHENTIK_EMAIL__TIMEOUT: ${AUTHENTIK_EMAIL__TIMEOUT}
>       - AUTHENTIK_EMAIL__FROM: ${AUTHENTIK_EMAIL__FROM}
>       - AUTHENTIK_EMAIL__TIMEOUT: 10
> ```
> 
> The email__from variable does not seem to be working correctly and defaulting to my email__username, however I will tinker to see if it is a configuration issue on my end.

You need to make sure that you have it setup in gmail if thats what you are using.  I have it working on my end if I send it from command line.  Just cant get it to work at all from events firing and getting the same error as OP

**Comment by davidjmorin** [comment]
![image](https://user-images.githubusercontent.com/9400895/213036799-839d8a3a-c074-4448-8ddf-3f4a0490c789.png)

**Comment by davidjmorin** [comment]
Ok sorry to post yet again.  I found the issue.  Use SSL and port 465.  TLS does not seem to work here at the moment.  This could be an unraid issue.

**Comment by adamzvolanek** [comment]
> Ok sorry to post yet again. I found the issue. Use SSL and port 465. TLS does not seem to work here at the moment. This could be an unraid issue.
> 
> ![image](https://user-images.githubusercontent.com/9400895/213037393-f0925945-5817-47ba-adcb-15b1dac2e093.png)

Sorry something I didn't mention in my solution. However yes, use SSL and port 465. I also had to use the more basic smtp.gmail.com rather than their relay.

**Comment by chupacabra71** [comment]
having a similar issue, i can send test emails using both SSL and TLS using ak test_email, but the flows don't send email using either.

**Comment by dav2000** [comment]
@chupacabra71 , were you able to find a solution? I am having exactly the same problem, with proton as email provider.
Using ak test_email works perfectly, but the email stage is not sending any emails.

**Comment by masterwishx** [comment]
Having issue to send mail via `ak test_email`
Using 465+TLS

**Comment by stephenpapierski** [comment]
I had the exact same behavior where the ak test_email would work fine, but using global smtp settings would fail with the exact same message as OP. Per [this](https://www.reddit.com/r/selfhosted/comments/10c6w7j/notes_about_email_setup_with_authentik/) thread, make sure you add the settings in both the authentik and authentik-worker containers.
<img width="322" alt="image" src="https://github.com/goauthentik/authentik/assets/5900005/d33db4de-ac74-42df-aa52-bff08a966ff9">

That way, I was able to get TLS working with smtp.gmail.com.
<img width="862" alt="Screenshot 2023-12-01 at 2 56 50 PM" src="https://github.com/goauthentik/authentik/assets/5900005/638364f8-313b-47b0-a228-bc5a16bd628e">

**Comment by masterwishx** [comment]
Fixed now .
Thanks for the info , im currently not using Authentik on Unraid , only in cloud with docker-compose + .env file.
My problem was port 465 not 587 !

**Comment by GD-Dal** [comment]
Another year passed, and this still isn't fixed.
I realize it's free, but when a "simple" thing like this never get fixed, what else can man expect.

time to move on

**Comment by asyncnomi** [comment]
Same issue here on 2024.12.2

My mail server support both:
* TCP + TLS initiation which is called STARTTLS (which authentik called TLS) on port 587
* Direct TLS session (which authentik called SSL) on port 465

When configuring the necessary settings in the docker compose environment both of those method result in a sucessfull ak test_email, but failed in flows.

The stack trace return two element:
* Object of type MIMEImage is not JSON serializable
* SMTPSenderRefused(502, b'5.7.0 Please authenticate first')

The second one is originated by my mail server rejecting the SMTP attempt to deliver an email due do no auth.
It's like celery is not taking into account the global settings correctly at all.

Disabling global setting in the email stage, and setting them again the connection settings of the stage did the trick.

It's definitely and "how are env settings passed to app" issue
