### ISSUE TITLE
blueprints: find another way to run reconcile than with dir()

### ISSUE THREAD

**Issue by rissson** [goauthentik/authentik#7852]
Now looking at it again I think there's probably a better way to do this than using `dir()` and then `getattr()`, probably something using a decorator?

Pseudo code:

```
@self.reconcile
def do_something(self):
    pass
```

(Not really part of this PR tbh)

_Originally posted by @BeryJu in https://github.com/goauthentik/authentik/pull/7590#discussion_r1422312556_

**Comment by rissson** [comment]
@BeryJu I think this has been somewhat resolved with the changes in #8454

**Comment by BeryJu** [comment]
yeah after playing around a bit with implementing this with a `@ManagedAppConfig.reconcile_tenant` decorator, that doesn't really help with code readability I think? It might still have an advantage to make it harder to accidentally misname a reconcile function and spend hours debugging why something isn't working
