### ISSUE TITLE
`2024.2.0` isn't tagged with `latest`

### ISSUE THREAD

**Issue by DenuxPlays** [goauthentik/authentik#8619]
The tag `2024.2.0` isn't tagged with the latest tag.
![image](https://github.com/goauthentik/authentik/assets/83671398/592103ab-c7be-44c2-ae30-3e064ef85f63)

**Comment by BeryJu** [comment]
thanks for letting us know, seems like there is still something slightly wrong in the updated CI process cc @rissson 

for now I've fixed this manually 
![image](https://github.com/goauthentik/authentik/assets/1932513/2c4bc802-2ede-4d23-989b-69724bf3360e)

**Comment by mc-fugger** [comment]
Hi @BeryJu,

unfortunately, the `latest` tag is still missing on the other containers [ldap](https://github.com/goauthentik/authentik/pkgs/container/ldap), [proxy](https://github.com/goauthentik/authentik/pkgs/container/proxy) and [radius](https://github.com/goauthentik/authentik/pkgs/container/radius)

**Comment by anony253** [comment]
This is happening again, there have been 2 releases, and they don't have the latest tag

**Comment by rissson** [comment]
@anony253 https://docs.goauthentik.io/docs/releases/2025.2#breaking-changes
